permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Ahkari
  email: gqz825584053@qq.com
  link: http://ahkari.github.io
  weibo: http://weibo.com/ahkari
  github: http://github.com/ahkari

# 站点信息
title: Ahkari的博客 
description: Ahkari的博客
url: http://ahkari.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://avatars1.githubusercontent.com/u/8937572?v=3&s=460
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: ahkari.github.io

# disqus 设置
disqus:
  shortname: ahkari-zh
